
name: Deploy to Amazon ECS

on:
  push:
    #branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        SHA: ${{ github.sha }}
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/instacar:$SHA .
        docker push ${{ steps.login-ecr.outputs.registry }}/instacar:$SHA
      shell: bash

    - name: Build, tag, and push image to Amazon ECR
      env:
        SHA: ${{ github.sha }}
        VERSION: ${{ github.ref_name }}
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/instacar:$SHA .
        docker tag ${{ steps.login-ecr.outputs.registry }}/instacar:$SHA ${{ steps.login-ecr.outputs.registry }}/instacar:$VERSION
        docker push ${{ steps.login-ecr.outputs.registry }}/instacar:$SHA
        docker push ${{ steps.login-ecr.outputs.registry }}/instacar:$VERSION
      shell: bash

    - name: Deploy to ECS
      id: deploy-esc
      env:
          SHA: ${{ github.sha }}
      run: |
        aws cloudformation deploy \
          --stack-name instacar \
          --template-file template.yaml \
          --parameter-overrides Tag=$SHA
      shell: bash
